version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./functions/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Install all needed dependencies from package.json
      - run:
          working_directory: ~/project/functions
          command: yarn install
      # Install all needed dependencies from package.json
      - run:
          working_directory: ~/project/functions
          command: yarn add -d firebase-tools
      - run:
          working_directory: ~/project/functions
          command: yarn deploy
      # Save the cache including node_modules folder
      - save_cache:
          paths:
            - ~/project/functions/node_modules
          key: v1-dependencies-{{ checksum "./functions/package.json" }}
